version: '3.8'

services:
  frontend:
    build:
      context: ../../frontend
      dockerfile: ../docker/frontend.dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=http://backend:5000
    depends_on:
      - backend

  backend:
    build:
      context: ../../backend
      dockerfile: ../docker/backend.dockerfile
    ports:
      - "5000:5000"
    volumes:
      - uploads:/app/app/static/uploads
      - outputs:/app/app/static/outputs
    environment:
      - FLASK_ENV=production
      - REDIS_URL=redis://redis:6379/0

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend

volumes:
  uploads:
  outputs:
